---
title: "ms_5"
author: "Suruchi Ramanujan"
date: "3/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# I want to load all necessary packages. 

library(dplyr)
library(janitor)
library(tidyverse)
library(ggthemes)
library(maps)
library(leaflet)
```


```{r}

# This first data set provides
# state-specific numbers from the CDC regarding the number of drug overdose
# deaths per state as well as the predicted numbers for drug overdose deaths. I
# am super excited to plot this graph onto a map and look at how the worst
# affected states change over time.

drugoverdosedeaths<- read.csv(
  "ms_6/VSRR_Provisional_Drug_Overdose_Death_Counts.csv") %>%
  clean_names() %>%
  select("state", "year", "month", "indicator", 
         "data_value", "state_name", "predicted_value") %>%
  
# I only want the information rows containing drug death information- I still
# need to decipher the difference between "Deaths" and "Drug Overdose Deaths"
# though.
  
 filter(str_detect(indicator, "Death")) %>%
  
# Ultimately, I want to look at state-specific data/trends so I want to group by
# state.
  
 group_by("state_name")
```


```{r}
# This data tracks the spending over a course of five years of a series of
# drugs. I want to compare the spending levels of the different kinds of drugs
# by categorizing them based on their use. Perhaps, we will find a correlation
# between spending and drug type for opioid deaths.

drugspending<-read.csv("Medicare Part B Drug Spending YTD 2017.csv", skip = 3) %>%
clean_names() %>%
  select("drug_description", "brand_name", "generic_name","x2013_total_spending", "x2013_total_dosage_units", "x2014_total_spending", "x2014_total_dosage_units", 
  "x2015_total_spending", "x2015_total_dosage_units", "x2016_total_spending", 
  "x2016_total_dosage_units", "x2017_total_spending", "x2017_total_dosage_units",
  "change_in_average_spending_per_dosage_unit_2016_2017", "annual_growth_rate_in_average_spending_per_dosage_unit_2013_2017")
```

```{r}

# This data set displays the number of deaths caused by opioids per county in NY
# over a course of 15 years.

deathbycounty_ny<- 
  read.csv("Vital_Statistics__Opioid-Related_Deaths_by_County__Beginning_2003.csv") %>%
  clean_names()

# Using data commons, I isolated drug spending in NY on some of the worst drugs
# of addiction and treatment drugs such as Methadone, Buprenorphine, and Naloxone.

drugspending_ny<- read.csv("New York Drug Spending.csv") %>%
  clean_names() %>%
  rename( Buprenorphine = "new_york_drug_dea_9064") %>%
  rename( Cocaine = "new_york_drug_dea_9041l") %>%
  rename( Methadone = "new_york_drug_dea_9250b") %>%
  rename( Naloxone = "new_york_drug_dea_9411") 

# I want to compare the drug spending in NY (a state that has a lot of opioid
# data with the country that has the worst opioid addiction rates, West
# Virginia)

drugspending_wv<- read.csv("West Virginia Drug Spending.csv") %>%
clean_names() %>%
  rename( Buprenorphine = "west_virginia_drug_dea_9064") %>%
  rename( Cocaine = "west_virginia_drug_dea_9041l") %>%
  rename( Methadone = "west_virginia_drug_dea_9250b") %>%
  rename( Naloxone = "west_virginia_drug_dea_9411") 

```

*The graphs below are new for this week. I don't know that I am satisfied with the readability of the last graph and will probably change it slightly in my final version.

```{r, echo = FALSE}

# For this week, I am going to plot the Drug Overdose Deaths in April of 2015 by
# state according to the CDC. I want to use this data just because it is the
# first recorded date of drug overdose deaths. I am hoping there will be some
# expected trend across states.

# I am not sure if this makes a difference but I am going to change the variable
# to be numeric (from factor) to rank later on.

drugoverdosedeaths$data_value <-as.numeric(drugoverdosedeaths$data_value)

# Here, I want to rank the deaths by state in descending order and filter them
# such that we are only looking at info from April of 2015.

drugodapr15<- drugoverdosedeaths %>%
  arrange(desc(data_value)) %>%
  select(state_name, `"state_name"`, data_value, indicator, month, year) %>%
  filter(year == "2015",
        month == "April",
        indicator == "Number of Drug Overdose Deaths") 
  
# Now, I want to ggplot the data. In the aesthetics, when I simply plot the
# state name vs data value, the data values do not rank in descending order
# despite specifying earlier, so I used the trick from PSet 3 of reordering in
# the x specifications.

ggplot(drugodapr15, aes(x= reorder(state_name,-data_value), y= data_value)) +
geom_col() +

# I want to label the title and x and y axes so that they are more descriptive.
  
labs(title = "Drug Overdose Deaths by State (April 2015)", 
     x = "State", 
     y = "Drug Overdose Deaths") +
  
# I changed the theme such that the backing of the graph is blank.
  
theme_classic()+ 

# The x axis details are cluttered so I chose to angle them for easy reading.
  
theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}

# I am going to do the same with July 2019, which is the latest date of
# recording. All code is the same except that the filter specifications at the
# start are for July of 2019 and I changed the title to specify July of 2019.

drugodjul19<- drugoverdosedeaths %>%
  arrange(desc(data_value)) %>%
  select(state_name, `"state_name"`, data_value, indicator, month, year) %>%
  filter(year == "2019",
        month == "July",
        indicator == "Number of Drug Overdose Deaths") 
  
ggplot(drugodjul19, aes(x= reorder(state_name,-data_value), y= data_value)) +
geom_col() +
labs(title = "Drug Overdose Deaths by State (July 2019)", 
     x = "State", 
     y = "Drug Overdose Deaths") +
theme_classic()+ 
theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r, echo = FALSE}

# I now want to look at how drug overdose death levels changed between 2019 and
# 2015 by state. To do so, I combined the two data tables from above using a
# full join.

difference_over_time<- drugodapr15 %>%
  full_join(drugodjul19, by = "state_name") %>%

# I also want to add a column which indicates the difference in deaths between
# the two data tables.
  
mutate(difference = data_value.y - data_value.x)

# I want to graph the difference over time by state with the x axis ranking the
# difference decrease.

ggplot(difference_over_time, aes(x= reorder(state_name,-difference), 
                                 y= difference)) +
geom_col() +

# I also changed the title label and the y axis label to specify the
# differences.
  
labs(title = 
    "Difference in Drug Overdose Deaths between April 2015 and July 2019", 
     x = "State", 
     y = "Difference in Drug Overdose Deaths") +

# I want the cleanest theme.
  
theme_classic()+ 

# I changed the labelling on the x axis to be less cluttered.

theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
library(shiny)
library(tidyverse)
library(gt)
library(dplyr)
library(ggplot2)
library(lubridate)

drugoverdosedeaths<- read.csv("ms_6/VSRR_Provisional_Drug_Overdose_Death_Counts.csv")

drugoverdosedeaths <- drugoverdosedeaths %>%
    clean_names() %>%
    select("state", "year", "month", "indicator", 
           "data_value", "state_name", "predicted_value") %>%
    filter(str_detect(indicator, "Drug Overdose Deaths")) %>%
    group_by("state_name") %>%
    mutate(time = paste(month, year, sep = " "))
drugoverdosedeaths$time<- as.factor(drugoverdosedeaths$time)
drugoverdosedeaths$time<- fct_relevel(drugoverdosedeaths$time, "January 2015", "February 2015", 
                                "March 2015", "April 2015", 
                                "May 2015", "June 2015", "July 2015", "August 2015", "September 2015", 
                                "October 2015", "November 2015", "December 2015", 
                                "January 2016", "February 2016", "March 2016", 
                                "April 2016", 
                                "May 2016", "June 2016", "July 2016", "August 2016", "September 2016", 
                                "October 2016", "November 2016", "December 2016", 
                                "January 2017", "February 2017", 
                                "March 2017", "April 2017", "May 2017", 
                                "June 2017", "July 2017", "August 2017", "September 2017", 
                                "October 2017", "November 2017", "December 2017", 
                                "January 2018", "February 2018", 
                                "March 2018", "April 2018", 
                                "May 2018", "June 2018", "July 2018", "August 2018", 
                                "September 2018", "October 2018", "November 2018", "December 2018",
                                "January 2019", "February 2019", 
                                "March 2019", "April 2019", 
                                "May 2019", "June 2019", "July 2019") 
drugoverdosedeaths$data_value <-as.numeric(drugoverdosedeaths$data_value)

drugoverdosedeaths2 <- drugoverdosedeaths %>%
 filter(time == "January 2015")

        ggplot(drugoverdosedeaths2, aes(x= reorder(state_name,-data_value), y= data_value)) +
            geom_col() +
            labs(title = "Drug Overdose Deaths by State Over Time", 
                 x = "State", 
                 y = "Drug Overdose Deaths") +
            
            theme_classic()+ 
            
            theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

```{r, message=FALSE}
#drug treatment centers

treatment_locations <- read_csv("Drug Treatment Centers.csv") %>%
  select(`Program Name`, Street, City, State, Zipcode)

us_state <- map_data("state") %>%
  rename(state_full = region)

# https://simplemaps.com/data/us-cities

longlatinfo <- read_csv("uscitieslonglat.csv") %>%
  rename(City = city) %>%
  rename(State = state_id)

treatment_locations_map <- treatment_locations %>%
  left_join(longlatinfo, by = c("City", "State")) %>%
  group_by(State) %>%
  mutate(count = n()) %>%
  mutate(state_name = tolower(state_name)) %>%
  rename(state_full = state_name) %>%
  left_join(us_state, by = "state_full") 

ggplot(data = treatment_locations_map,
            mapping = aes(x = long, y = lat.y,
                          fill = count, group = group)) + 
  geom_polygon(color = "gray90", size = 0.05) + 
  theme_map() +
  scale_fill_gradient(low = "white", high = "#CB454A",
                      breaks = c(0,20,40,60,80,120)) +
    guides(fill = guide_legend(nrow = 1)) + 
    theme(legend.position = "bottom") +
  labs(title = "Distribution of Opioid Treatment Centers in 2020",
       color = "Number of Treatment Centers in State")

# per capita pop data taken from https://www.census.gov/data/tables/time-series/demo/popest/2010s-state-total.html#par_textimage

state_pop <- read_csv("State Population Estimate.csv") %>%
  select(NAME, POPESTIMATE2019) %>%
  rename(state_full = NAME) %>%
  mutate(state_full = tolower(state_full))

treatment_locations_map_per_cap <- treatment_locations_map %>%
  left_join(state_pop, by = "state_full") %>%
  group_by(State) %>%
  mutate(count_per_pop = n()/POPESTIMATE2019)

ggplot(data = treatment_locations_map_per_cap,
            mapping = aes(x = long, y = lat.y,
                          fill = count_per_pop, group = group)) + 
  geom_polygon(color = "gray90", size = 0.05) + 
  theme_map() +
  scale_fill_gradient(low = "white", high = "#CB454A",
                      breaks = c(0,20,40,60,80,120)) +
    guides(fill = guide_legend(nrow = 1)) + 
    theme(legend.position = "bottom") +
  labs(title = "Distribution of Opioid Treatment Centers in 2020 (Per Capita)",
       color = "Number of Treatment Centers in State Per Capita")
```



```{r, message = FALSE}
#MA specific data

madeathbyagegender <- read_csv("MAFatalOpioidOverdosesByAgeAndGender.csv")

macountyheroin <- read_csv("MAHeroinAsPrimarySubstanceOfUse.csv")

madeathbyrace <- read_csv("MAOpioidDeathsByRaceAndEthnicity.csv")

matypeofsubstance <- read_csv("MAPrimarySubstanceofUseWhenEnteringTreatmentbyTown.csv")

toxdeath <- read_csv("MAProportionDecedentsWithRxHistorybyToxicologyScreen.csv",
         skip = 1)

```

```{r}
mavsus_death <- read_csv("MAAgeAdjustedOpioidRelatedDeathRateByYear.csv")

mavsus_death <- mavsus_death %>%
  group_by(Geography) %>%
  filter (Year != "2015") %>%
  filter (Year != "1999") %>%
  rename(deathperhundredthousand =`Age-Adjusted Opioid-Related Death Rate per 100,000 People`)

ggplot(mavsus_death, aes(x = Year, y = as.numeric(deathperhundredthousand), color = Geography)) +
  geom_line() +
theme_classic() +
  labs(x = "Year",
       y = "Deaths per 100,000",
       title = "Comparison of Death Rates between Massachusetts and the United States",
       subtitle = "Between the Years of 2000 and 2014") 
```

```{r}
counties <- read_csv("zip_codes_states.csv") %>%
  filter(state == "MA") %>%
  rename(County = county) %>%
  rename(Municipality = city)

madeathbycounty <- read_csv("MAAverageAnnualOpioidRelatedDeathRateper100,000People.csv")

countypop <- read_csv("countypop.csv") %>%
  mutate(Pop = Pop/100000) %>%
  rename(subregion = CTYNAME) %>%
  mutate(subregion = tolower(subregion)) %>%
  select(subregion, Pop)

madeathbycountywlonglat <- madeathbycounty %>%
  left_join(counties, by = "Municipality")

madeathbycountywlonglat <- madeathbycountywlonglat %>%
  select(County,
         `Confirmed Opioid Related Death Count 2001-2005`,
         `Confirmed Opioid Related Death Count 2006-2010`,
         `Confirmed Opioid Related Death Count 2011-2015`,
         `latitude`,
         `longitude`,
         `Municipality`) %>%
  distinct(Municipality, .keep_all= TRUE) %>%
  na.omit() %>%
  rename(subregion = County) %>%
  mutate(subregion = tolower(subregion)) %>%
  group_by(subregion) %>%
  mutate(total_deaths_2001.5 = sum(`Confirmed Opioid Related Death Count 2001-2005`)) %>%
  mutate(total_deaths_2006.10 = sum(`Confirmed Opioid Related Death Count 2006-2010`)) %>%
  mutate(total_deaths_2011.15 = sum(`Confirmed Opioid Related Death Count 2011-2015`)) %>%
  distinct(subregion, .keep_all= TRUE)
  

us_county <- map_data("county") %>%
  filter(region == "massachusetts")

# https://www.indexmundi.com/facts/united-states/quick-facts/massachusetts/percent-of-people-of-all-ages-in-poverty#table

povertybycounty <- read_csv("PovertyByCounty.csv") %>%
  rename(subregion = County) %>%
  mutate(subregion = tolower(subregion))

full_data <- us_county %>%
  left_join(madeathbycountywlonglat, by = "subregion") %>%
  left_join(countypop, by = "subregion") %>%
  left_join(povertybycounty, by = "subregion") %>%
  mutate(percap_2001.5 = total_deaths_2001.5/Pop) %>%
  mutate(percap_2006.10 = total_deaths_2006.10/Pop) %>%
  mutate(percap_2011.15 = total_deaths_2011.15/Pop) 

ggplot(full_data, aes(x = `Poverty Percent`, y = percap_2001.5)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

full_data %>%
  summarize(correlation = cor(percap_2001.5,`Poverty Percent`))

ggplot(full_data, aes(x = `Poverty Percent`, y = percap_2006.10)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

full_data %>%
  summarize(correlation = cor(percap_2006.10,`Poverty Percent`))

ggplot(full_data, aes(x = `Poverty Percent`, y = percap_2011.15)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

full_data %>%
  summarize(correlation = cor(percap_2011.15,`Poverty Percent`))

ggplot(data = full_data,
            mapping = aes(x = long, y = lat,
                          fill = `Poverty Percent`,
                          group = group)) + 
  geom_polygon(color = "gray90", size = 0.05) + 
  theme_map() +
  scale_fill_gradient(low = "white", high = "#CB454A",
                      breaks = c(0,2,4,6,8,10)) +
    guides(fill = guide_legend(nrow = 1)) + 
    theme(legend.position = "bottom")

ggplot(data = full_data,
            mapping = aes(x = long, y = lat,
                          fill = percap_2001.5,
                          group = group)) + 
  geom_polygon(color = "gray90", size = 0.05) + 
  theme_map() +
  scale_fill_gradient(low = "white", high = "#CB454A",
                      breaks = c(0,20,40,60,80,100)) +
    guides(fill = guide_legend(nrow = 1)) + 
    theme(legend.position = "bottom")

ggplot(data = full_data,
            mapping = aes(x = long, y = lat,
                          fill = percap_2006.10,
                          group = group)) + 
  geom_polygon(color = "gray90", size = 0.05) + 
  theme_map() +
  scale_fill_gradient(low = "white", high = "#CB454A",
                      breaks = c(0,20,40,60,80,100)) +
    guides(fill = guide_legend(nrow = 1)) + 
    theme(legend.position = "bottom")

ggplot(data = full_data,
            mapping = aes(x = long, y = lat,
                          fill = percap_2011.15,
                          group = group)) + 
  geom_polygon(color = "gray90", size = 0.05) + 
  theme_map() +
  scale_fill_gradient(low = "white", high = "#CB454A",
                      breaks = c(0,20,40,60,80,100)) +
    guides(fill = guide_legend(nrow = 1)) + 
    theme(legend.position = "bottom")

# don't put these in final app

ggplot(data = full_data,
            mapping = aes(x = long, y = lat,
                          fill = total_deaths_2001.5,
                          group = group)) + 
  geom_polygon(color = "gray90", size = 0.05) + 
  theme_map() +
  scale_fill_gradient(low = "white", high = "#CB454A",
                      breaks = c(0,100,200,300,400,500,600)) +
    guides(fill = guide_legend(nrow = 1)) + 
    theme(legend.position = "bottom")

ggplot(data = full_data,
            mapping = aes(x = long, y = lat,
                          fill = total_deaths_2006.10,
                          group = group)) + 
  geom_polygon(color = "gray90", size = 0.05) + 
  theme_map() +
  scale_fill_gradient(low = "white", high = "#CB454A",
                      breaks = c(0,100,200,300,400,500,600)) +
    guides(fill = guide_legend(nrow = 1)) + 
    theme(legend.position = "bottom")

ggplot(data = full_data,
            mapping = aes(x = long, y = lat,
                          fill = total_deaths_2011.15,
                          group = group)) + 
  geom_polygon(color = "gray90", size = 0.05) + 
  theme_map() +
  scale_fill_gradient(low = "white", high = "#CB454A",
                      breaks = c(0,100,200,300,400,500,600)) +
    guides(fill = guide_legend(nrow = 1)) + 
    theme(legend.position = "bottom")

```

```{r}

#treatment centers in MA

treatment_locations_map_mas <- treatment_locations %>%
  left_join(longlatinfo, by = c("City", "State")) %>%
  filter(State == "MA") %>%
  drop_na()


leaflet(options = leafletOptions(dragging = TRUE,
                                 minZoom = 8, 
                                 maxZoom = 10)) %>%
  addProviderTiles("CartoDB") %>%
  addCircleMarkers(data = treatment_locations_map_mas,
                   radius = 3,
                   label = ~`Program Name`) 

# need to figure this out bc color isnt working
 # addLegend(position = "bottomright", colors = "#0000FF", title = "Opioid Treatment Sites")
  
```

